import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Not source: git worktrees the agent harness checks out here. They are
    // whole copies of the repo at other commits, so linting them reports this
    // project's files two and three times over, at whatever state that branch
    // left them in. No rule is relaxed by this; the scope is.
    ".claude/**",
    // Generated by `npm run test:coverage`.
    "coverage/**",
  ]),
]);

export default eslintConfig;
